# add dotnet image
image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

variables:
    FTP_HOST: "ftp://waws-prod-db3-127.ftp.azurewebsites.windows.net"
    FTP_USER_YML: $FTP_USERNAME
    FTP_PASS_YML: $FTP_PASSWORD_NEW

stages:
    - test
    - build
    - deploy
    

# RUN TESTS
test:
    stage: test
    script: dotnet test
    

# BUILD PROJECT
build:
  stage: build
  script: dotnet build --configuration Release


# DEPLOY TO AZURE APP SERVICE USING FTP
# 1. build/publish dotnet project
# 2. install lftp package
# 3. push release folder using ftp to azure web application
deploy:
  stage: deploy
  script:
    - echo "Deploying to staging server"
    - dotnet publish --configuration Release
    - apt-get update -qq && apt-get install -y -qq lftp
    - echo "vars" $FTP_USER_YML $FTP_USERNAME $FTP_PASSWORD $FTP_PASS_YML
    - lftp -e "set ftp:ssl-allow no; open -u $FTP_USER_YML,$FTP_PASS_YML $FTP_HOST; mirror -Rev ./devopsapi/bin/Release/netcoreapp2.2/publish ./site/wwwroot; bye"
  only:
  - master
