// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace devopsapi.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Account = new HashSet<Account>();
        }

        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string Firstname { get; set; }
        [StringLength(50)]
        public string Lastname { get; set; }
        public long? BankId { get; set; }
        [StringLength(50)]
        public string Psw { get; set; }

        [ForeignKey(nameof(BankId))]
        [InverseProperty("Customer")]
        public virtual Bank Bank { get; set; }
        [InverseProperty("BankNavigation")]
        public virtual ICollection<Account> Account { get; set; }
    }
}