// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace devopsapi.Models
{
    public partial class Transaction
    {
        [Key]
        public long Id { get; set; }
        [StringLength(20)]
        public string IBAN { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Amount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TimeStamp { get; set; }

        [ForeignKey(nameof(IBAN))]
        [InverseProperty(nameof(Account.Transaction))]
        public virtual Account IBANNavigation { get; set; }
    }
}